server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://qic534o8o0.execute-api.us-east-1.amazonaws.com/;
        proxy_set_header Host qic534o8o0.execute-api.us-east-1.amazonaws.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}
