name: CI/CD Backend Pipeline

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobar el código
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Buscar POM y Construir con Maven
        run: |
          POM_PATH=$(find . -name "pom.xml" | head -n 1)
          if [ -z "$POM_PATH" ]; then
            echo "ERROR: ¡No se encontró ningún archivo pom.xml en ningún lado!"
            exit 1
          fi
          POM_DIR=$(dirname "$POM_PATH")
          echo "Pom encontrado en: $POM_DIR"
          echo "POM_DIR=$POM_DIR" >> $GITHUB_ENV
          cd "$POM_DIR"
          mvn clean package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Iniciar sesión en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir y subir imagen a ECR
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.POM_DIR }}
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/repo-proyecto-ep2:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en EC2 vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}
            docker pull ${{ secrets.AWS_ECR_REGISTRY }}/repo-proyecto-ep2:latest
            docker stop backend-app || true
            docker rm backend-app || true
            docker run -d --name backend-app -p 8080:8080 ${{ secrets.AWS_ECR_REGISTRY }}/repo-proyecto-ep2:latest