name: CI/CD Frontend Pipeline (ECS Deploy)

on:
  push:
    branches: [ "deploy" ]  # Se ejecuta cuando mandas cambios a esta rama

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobar el código
        uses: actions/checkout@v4

      - name: Configurar Node.js (Para validar el entorno React)
        uses: actions/setup-node@v4
        with:
          node-node-version: '18'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Iniciar sesión en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir y subir imagen Frontend a ECR
        uses: docker/build-push-action@v5
        with:
          context: ./front_despacho  # Entra directo a compilar la carpeta del front
          push: true
          tags: 640175238127.dkr.ecr.us-east-1.amazonaws.com/proyecto-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales AWS para Deploy
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Actualizar Servicio Frontend en AWS ECS Fargate
        run: |
          aws ecs update-service --cluster cluster-innovatech --service servicio-frontend --force-new-deployment